# Generated by Django 2.2.7 on 2019-11-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="media", name="hash_value"),
        migrations.AlterField(
            model_name="metafields",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_fields",
                to="app.Media",
            ),
        ),
        migrations.AlterField(
            model_name="metafields",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
